apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-service
  labels:
    app: log-service
    component: logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-service
  template:
    metadata:
      labels:
        app: log-service
    spec:
      containers:
      - name: log-service
        image: pipelinedave/log-service:469e01906904a783aaabff291712bfcbf3893f95
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DATABASE_URL
          value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@staging-postgres:5432/choretwo?schema=logs&sslmode=disable
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: choretwo-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: choretwo-secrets
              key: postgres-password
        - name: REDIS_URL
          value: redis://redis:6379
        - name: AUTH_SERVICE_URL
          value: http://auth-service:80
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always
