apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: choretwo-client-secret
  namespace: dex
spec:
  encryptedData:
    CHORETWO_CLIENT_SECRET: AgB9Pe6Yb9xXA0HgM2ypoeTusqpwkFZVBf3VZ5rYp22CTdDeKHcF6ST/3LUxsxslL58whNFCxdMmrjvVP1fBGzAOivpXWY/xKANLpyZJ1WOEENng4MnQmLswWx2Ut4DPI6qjebcwJyo3/T/9VdnqYPB9pG/U24SiH6s8bAXOCUmiP1KfLA4EZdM4lvy9bTmAMV0XZdrLPFwCcFesm/2NhwleIGDI3/pZDFxZsQlEM5+IIApxh8A8FhcJjc6bwuTy0UX2Yzsj+HvD0FFs97jSSOyU+KfBtcU+6hrQCup/SCHTswgMG32MeMAiqQu5R3mE47T2EztRRE6ODyM4ZhXfBvNZAPv1CdlzcBxYukY7h5pU1CUrDn8Z3TtM4ao6wTq4BSwRafZB2enyCqabg+1zNn0gu5yqBGLKRk9hyU/1R2Mv2+xjyweuu3xwnS9FRnFpkAcPW82KrtnOYRD0S3/sMQkP1CikRZlctXK3jPD7EQkyAi9WcZNDWyz6YixSE6Ima8QYKDRHuDOeU5s90PVcZ39duX3GpAm7SPBo345yR9RZcUGmIKee929bqEmykfpUr5pjxxLp1pgAYrxuuoe0+Xv1AaebRfShEfBzcDPCvz8s7ljBvnmeiV6BQr3VCYQL/scPNMIzNHA1QAIGw7N1xj6XdaSD/omEzNhWnNB3NK69L/DSTFcsSWy8Ub9QOwusOc+suR7+k4Y6kOCyZ41H46lbJGm5LygAksTrLOwXOvJHjNY4ldlf1OSbAghAm3UslRo=
  template:
    metadata:
      annotations:
        description: Unsealed Dex client secret for Choretwo. Intended for use with
          SealedSecrets.
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: choretwo-client-secret
        app.kubernetes.io/instance: dex
        app.kubernetes.io/managed-by: flux
        app.kubernetes.io/name: dex
        app.kubernetes.io/part-of: dex
      name: choretwo-client-secret
      namespace: dex
    type: Opaque
---
