apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
namespace: choretwo-staging
commonLabels:
  environment: staging

images:
- name: pipelinedave/frontend
  newTag: 4eb950ecb29e17ffcd50f8d58a0b9a0364c7bb61

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: USE_MOCK_AUTH
        value: "true"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: SERVER_URL
        value: "https://choretwo-staging.stillon.top"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: FRONTEND_URL
        value: "https://choretwo-staging.stillon.top"
  target:
    kind: Deployment
    name: auth-service
