apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
namespace: choretwo-staging
commonLabels:
  environment: staging

images:
- name: pipelinedave/ai-copilot-service
  newName: pipelinedave/ai-copilot-service
  newTag: 857bb5a638555e316917c74415889088380e21e8
- name: pipelinedave/auth-service
  newName: pipelinedave/auth-service
  newTag: 857bb5a638555e316917c74415889088380e21e8
- name: pipelinedave/frontend
  newName: pipelinedave/frontend
  newTag: 857bb5a638555e316917c74415889088380e21e8
- name: pipelinedave/monolith
  newName: pipelinedave/monolith
  newTag: 857bb5a638555e316917c74415889088380e21e8

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: USE_MOCK_AUTH
        value: "true"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: SERVER_URL
        value: "https://choretwo-staging.stillon.top"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: FRONTEND_URL
        value: "https://choretwo-staging.stillon.top"
  target:
    kind: Deployment
    name: auth-service
