apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
namespace: choretwo-staging
commonLabels:
  environment: staging

images:
- name: pipelinedave/frontend
  newTag: 7bbab627ad98036c5ea2b8f3ff6c4c253f0a36fb

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: USE_MOCK_AUTH
        value: "true"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: SERVER_URL
        value: "https://choretwo-staging.stillon.top"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: FRONTEND_URL
        value: "https://choretwo-staging.stillon.top"
  target:
    kind: Deployment
    name: auth-service
