apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
namespace: choretwo-production
commonLabels:
  environment: production

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: SERVER_URL
        value: "https://choretwo.stillon.top"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: FRONTEND_URL
        value: "https://choretwo.stillon.top"
  target:
    kind: Deployment
    name: auth-service
