apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
namespace: choretwo-production
commonLabels:
  environment: production

images:
- name: pipelinedave/ai-copilot-service
  newName: pipelinedave/ai-copilot-service
  newTag: 82f3085c0379b32fcdc490222951143b39dee45a
- name: pipelinedave/auth-service
  newName: pipelinedave/auth-service
  newTag: 82f3085c0379b32fcdc490222951143b39dee45a
- name: pipelinedave/frontend
  newName: pipelinedave/frontend
  newTag: 82f3085c0379b32fcdc490222951143b39dee45a
- name: pipelinedave/monolith
  newName: pipelinedave/monolith
  newTag: 82f3085c0379b32fcdc490222951143b39dee45a

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: SERVER_URL
        value: "https://choretwo.stillon.top"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: FRONTEND_URL
        value: "https://choretwo.stillon.top"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: HTTPS_ONLY
        value: "true"
  target:
    kind: Deployment
    name: auth-service
