apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
namespace: choretwo-production
commonLabels:
  environment: production

images:
- name: pipelinedave/frontend
  newTag: 33ceadb1df61bb3cc48514675621346b99e5f0b4
- name: pipelinedave/monolith
  newTag: f971dde0e5dd44bef40c7ffc69bb5d69c0d4dad8
- name: pipelinedave/auth-service
  newTag: 7791e6798c298cbbb82a40062ae585e9b22a2368

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: SERVER_URL
        value: "https://choretwo.stillon.top"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: FRONTEND_URL
        value: "https://choretwo.stillon.top"
  target:
    kind: Deployment
    name: auth-service
