apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
  labels:
    app: monolith
    component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolith
  template:
    metadata:
      labels:
        app: monolith
    spec:
      containers:
      - name: monolith
        image: pipelinedave/monolith:<TAG>
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 150Mi
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: choretwo-secrets
              key: database-url
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: choretwo-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: choretwo-secrets
              key: postgres-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: choretwo-secrets
              key: jwt-secret
        - name: REDIS_URL
          value: redis://redis:6379
        - name: GATWAY_URL
          value: https://gotify.stillon.top
        - name: OLLAMA_URL
          value: http://host.docker.internal:11434
        - name: AI_MODEL
          value: mistral
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always
