apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: choremane-oauth-secret
  namespace: choremane-prod
spec:
  encryptedData:
    OAUTH_CLIENT_SECRET: AgB9TqEA8qKtmyzN50voZ6HK96FRk/5gVaZD6Uf+5d5/4Q6AIhuXiahrGWvD6raQYDG/HTweEVPtlUgbbI/5+DNLl2u2+Ib4I7dCiLGKb5g1bLZ0nieocp15ZL0bnaVXsqGV1DhUa33bTVpW+WgbHiIia0B7cgSiERMrDcsT55x7KcwGvHTO3SkIhscGPBqevM1ZIA2FxZdJhpQGaZU8P4jWh2dxZZpUMEQoAt0luXeL5UJ+xUK7SC30WF4G8H6rm8xQ1V16EhuVuqSKu0cXoHCAiuiD7oCj9ns4tqEkiIqZEN34i2i9xZguNFdeSzTFCBGns6R2UEk+B3VKtLY25/Ros37/D71RGj2Hc/oBtg2QydUvx4ibXoEoboIP2tqea0XUch17abjeDLq8znuO6H1N8pEluMWWAXUglFzOM/3bXX7ETCgubSMjIh4zAtSCNxUOpwXAnQVaNLccAuZCnNomHtcbSI/pl15law6hikNcQKv0vNvwQlGFDko7sSYJDgcijsR+xkSELBhCFcw0t0kc3ArRJdOIEoTuLKJkt3fPODE5yFbMurDlc+0rG8sGcUMLrS7ieCJfaFXQjJ9wBR8yP+5bBzs/NwxhDlzAYGFxMW66HSfpdTqmfXRE6CeZkY40u26OpmOrexIRdcNv+r0zTDhORYtpwHuoPuE+xbnnhNk9UKycG05jGYiuK+MavfRWBGpRre7Kyn1JltEabuMp
  template:
    metadata:
      creationTimestamp: null
      name: choremane-oauth-secret
      namespace: choremane-prod
    type: Opaque
---
