apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgres/
- redis/
- auth-service/
- chore-service/
- log-service/
- notification-service/
- ai-copilot-service/
- frontend/
- ingress.yaml
