apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-tunnel
  namespace: flux-system
spec:
  interval: 1h
  prune: true
  suspend: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kustomize/cloudflare-tunnel
  targetNamespace: kube-system
  wait: true
  timeout: 5m
  dependsOn:
    - name: nginx-ingress
