apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nginx-ingress.yaml
- cert-manager.yaml
- dex.yaml
- choremane-prod.yaml
- choretwo-staging.yaml
- picoshare.yaml
- cloudflare-tunnel.yaml
