apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: matrix-conduit
  namespace: flux-system
spec:
  targetNamespace: matrix
  interval: 5m
  path: ./kustomize/matrix-conduit
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 2m
