apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../picoshare
patches:
- target:
    kind: PersistentVolumeClaim
    name: picoshare-pvc
    namespace: picoshare
  patch: |-
    - op: remove
      path: /spec/volumeName
- path: image-patch.yaml
  target:
    kind: Deployment
    name: picoshare
    namespace: picoshare
