apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: arr-secrets
  namespace: media-server
spec:
  encryptedData:
    radarr-api-key: AgCjySQyPB6hTWiH5+sUXTSer7iewhuEKdxIVyesE/N6N7D8qRTvc7e+Hclpe2mF55TalfGVvRhBUVT83ID1OnWw4giORL5acooYYJVNTjvsD0p+C07X3Pk/XDtq2rrUF9dDjriTl5lP+6N2c4mxNbSL2bajkaRJL+utXQqDHvoS/FvT7Et3IgFI/E/TEVrpWSDolvChS8dvzlkJi+4SoS34pTLwxFoub32/YMymnn2RQXIln+i9z3y6rYEvJ/0B6Ey9gyT2XV9gTvrgCab4wFffBKcan6H9Guq0aFhupJddidyyYf9JAdy72DbfKhuQB9fYhvOFLmJFGI2ca+jyFYejbG0+iz2u6p165urLBCCFygTD3HtBSPtOtBVlihO5DvfKt3nL9pnkFNS9OjShR9w2tFtowb3eT++lr6vVIlrqGtoE/Vy0M+jdGAjuzHBbeaAYkiP0qu6cvkcrLSILdYVBlVUoaXfbLbbQWLl1KlUo+HXYsH3kdhdbTxOsD78lcOw1IPOFcwMKkpUBx95EkRfVaYjI0jpWm/Aip1Uz6G6V3X70TA68EpYl42ZS2SuBz/Xxg7MHsgODog8krO+5rY3z13MOOkobzDu3Zju0lxDD+ZdEeJ9X2lWCId28FiZ6bVE5oenMu94bm64Pl0QXmc5Af5+9Cb6ChQkufQNpxDnwV1Lu5oSTQ5Ib8c2o4kTKbm3YVkkUTLet/3N7kUwKJ9hXG39x1daC0Ww=
    sonarr-api-key: AgCIV4bAeHtATlo/ecqmkWeMwShytNPnyBR59RLxJu7AlNM9kqEg2w1aTU4ws9508qfF7+V8EQ9JO+kZ3O0mPTNd4mUhU9DNDIm1LZEnmrHhESa6Ee5BGTiOl0yCVrxMXqSFVz4lIwoxSIvgqcA3Y3ZgSBq5gybf1byDOCNlsCbHGl7uY4G99t2/75Jp1m/bTpfbmnL9KQro9CKCbwdQvyQxQKEKwg3p/b4A1+e7woudnEMQ46xmnk3+VG9rccEulpn/V5wbn8zeqiSivM51F9d1HoEYbWsKkiY6XbpMHH7qUr6HnoguxOsKPA6cXxYFVNwiiesqDFLErJhTUIVsm2WkihL2Gj4PMxNSVwkO1EF6XUJdyGFMmOrpA9BfJW2rsNzl0j/5m8ATx63g4eboo3WLxwVDwOyCBFlpwDZkquvhFJWFP+8y054WH6CeSFH29TSgaXBISNWJwcHPwh6knD5OZo2+aIrBLIJUcsne7bS08lJz25T0LuvaYR2g4h+rxxmaKPDSKuY0LdB2dqghR5Zkm5PeNtXzN0e9FFdSVnGhofGu8hTfrrSgwixkkRWswpC0ipSZD+RaupBwUdt9m6d3idqygKJJMqPKaA4N3AOzFrday4ufgU3Lvy7SB5zPqPcfJPBJhpZeOVgNhEP84m67Q04LCZhZRMbKA4f78Ai+e56a7aNklu9KZZ6diEuRBBQTwxERmU45023CHEYSWMBMFwYpGGgRJAI=
  template:
    metadata:
      creationTimestamp: null
      name: arr-secrets
      namespace: media-server
    type: Opaque
---
