apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: matrix-conduit-storage
  namespace: matrix
  labels:
    app.kubernetes.io/name: matrix-conduit
    app.kubernetes.io/instance: matrix-conduit
    app.kubernetes.io/version: "v0.10.13"
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: matrix-conduit
    app.kubernetes.io/managed-by: flux
  annotations:
    description: "PersistentVolumeClaim fuer Conduit-Daten (RocksDB)"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeMode: Filesystem
